name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Prefect Default Worker Docker image
        run: docker build . --file default/Dockerfile --tag glynfinck/prefect-default-worker:latest

  push_to_registry:
    name: Push the Prefect Default Worker Docker Image to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Prefect Default Worker Docker Image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: default/
          push: true
          tags: glynfinck/prefect-default-worker:latest
