name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Prefect Default Worker Docker image
        run: docker build . --file default/Dockerfile --tag glynfinck/prefect-default-worker:$(date +%s)
